version: "3.7"
services:
  followerserver:
    build:
      context: ./follower-microservice/
      dockerfile: Dockerfile
    image: followerdocker
    container_name: aplikacijafollower
    restart: always
    networks:
      - followerserver
    ports:
      - 8089:8089
    environment:
      - PORT=8089
      # NoSQL: environment variable holding connection URI for Neo4J database
      # Local DB instance
      - NEO4J_DB=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASS=Dejann03
    depends_on:
      neo4j:
        condition: service_healthy

  neo4j:
    image: neo4j
    container_name: neo4jfollower
    restart: always
    networks:
      - followerserver
    ports:
      - "7687:7687"
      - "7474:7474"
      - "7473:7473"
         # Docker healtcheck - checks if database is "alive"
    healthcheck:
      # test: [ "CMD-SHELL", "echo RETURN 1 | cypher-shell -a <NEO4J_dbms_connector_bolt_listen__address> -u <user defined username> -p <user defined password> || exit 1" ]
      test:
        [
          "CMD-SHELL",
          "echo RETURN 1 | cypher-shell -a bolt://neo4j:7687 -u neo4j -p Dejann03 || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 10 
    environment:
      - NEO4J_AUTH=neo4j/Dejann03
    volumes:
      - database-data:/data

volumes:
  database-data:
    name: server-databasefollower


networks:
  followerserver:
    name: followerserver
    driver: bridge

